kind: Service
apiVersion: v1
metadata:
  name: iperf
  labels:
    app: iperf
  namespace: iperf
spec:
  type: NodePort
  ports:
    - name: iperf
      port: 5001
      nodePort: 5001
      protocol: TCP
  selector:
    app: iperf
