apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redirector
  name: redirector
  namespace: osm-replicate-sequences
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: redirector
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redirector
    spec:
      containers:
      - name: redirector
        image: mazdermind/redirector:latest

        env:
        - name: REDIRECT_000_OLD_LOCATION
          value: /replicate-sequences:https://replicate-sequences.osm.kube.mazdermind.de/

        - name: REDIRECT_001_ROOT
          value: /:https://replicate-sequences.osm.kube.mazdermind.de/
