apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lampi
  name: lampi
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: lampi
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lampi
    spec:
      containers:
      - name: lampi
        image: mazdermind/lampi