apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: data
  namespace: {{ namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
