apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: forum
  name: forum
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: forum
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forum
    spec:
      containers:
      - name: forum
        image: mazdermind/php-54-apache-mysql

        volumeMounts:
        - mountPath: /var/www/html
          name: forum

      volumes:
      - name: forum
        persistentVolumeClaim:
          claimName: forum
