apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: debian:latest
    command: ['sh', '-c', 'while true; do sleep 1000; done']

    volumeMounts:
    - mountPath: /data/db
      name: data

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test
