kind: Service
apiVersion: v1
metadata:
  name: owncloud
  labels:
    app: owncloud
  namespace: owncloud
spec:
  ports:
    - name: www
      port: 80
      protocol: TCP
  selector:
    app: owncloud
