---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: traefik-conf
data:
  traefik.toml: |
    # traefik.toml
    logLevel = "DEBUG"
    defaultEntryPoints = ["http", "https"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"

      [entryPoints.http.redirect]
      entryPoint = "https"

      [entryPoints.https]
      address = ":443"

      [entryPoints.https.tls]

    [kubernetes]

    [web]
    address = "127.0.0.1:8080"

    [acme]
    email = "peter@mazdermind.de"
    storage = "/etc/traefik/acme/acme.json"
    entryPoint = "https"
    onHostRule = true
    acmeLogging = true
