apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: redirector
  name: redirector
  namespace: www
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: www.mazdermind.de
    http:
      paths:
      - backend:
          serviceName: redirector
          servicePort: web
