apiVersion: v1
kind: Secret
metadata:
  name: mail-forwarder
  namespace: {{ namespace }}
type: Opaque
data:
  relay_user: {{ ['Privat', 'NetCup', 'kube', namespace, 'relay'] | keepass('username') | base64 }}
  relay_pass: {{ ['Privat', 'NetCup', 'kube', namespace, 'relay'] | keepass('password') | base64 }}
