kind: Service
apiVersion: v1
metadata:
  name: forwarder
  labels:
    app: forwarder
  namespace: {{ namespace }}
spec:
  ports:
    - name: forwarder
      port: 25
      protocol: TCP
  selector:
    app: forwarder
