apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db_root_pass: {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql root'] | keepass_password | base64 }}

  db_user:      {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql user'] | keepass_username | base64 }}
  db_pass:      {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql user'] | keepass_password | base64 }}
