apiVersion: v1
kind: Secret
metadata:
  name: osm-replicate-sequences
  namespace: {{ namespace }}
type: Opaque
data:
  db_root_pass: {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql root'] | keepass('password') | base64 }}

  db_user:      {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql user'] | keepass('username') | base64 }}
  db_pass:      {{ ['Privat', 'NetCup', 'kube', namespace, 'mysql user'] | keepass('password') | base64 }}
