apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: updater
  name: updater
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: updater
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: updater
    spec:
      containers:
      - name: updater
        image: mazdermind/replicate-sequences:latest

        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: osm-replicate-sequences
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osm-replicate-sequences
              key: db_pass
        - name: DB_NAME
          value: osm

        - name: DB_HOST
          value: mysql

        - name: ABUSE_MAIL
          value: osm@mazdermind.de
