apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: osm-replicate-sequences
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: mazdermind/replicate-sequences:latest
        command: ["apache2-foreground"]

        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: osm-replicate-sequences
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: osm-replicate-sequences
              key: db_pass
        - name: DB_NAME
          value: osm

        - name: DB_HOST
          value: mysql

        - name: ABUSE_MAIL
          value: osm@mazdermind.de
