apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup
  labels:
    app: backup
  namespace: {{ namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
