apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  labels:
    app: database
  namespace: {{ namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
