kind: Service
apiVersion: v1
metadata:
  name: ejabberd
  labels:
    app: ejabberd
  namespace: {{ namespace }}
spec:
  ports:
    - name: ejabberd
      port: 5280
      protocol: TCP
  selector:
    app: ejabberd
