apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload
  labels:
    app: upload
  namespace: {{ namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
