kind: Service
apiVersion: v1
metadata:
  name: monit
  labels:
    app: monit
  namespace: monit
spec:
  ports:
    - name: monit
      port: 2812
      protocol: TCP

    - name: check-receiver
      port: 8080
      protocol: TCP

  selector:
    app: monit
