kind: Service
apiVersion: v1
metadata:
  name: check-receiver
  labels:
    app: check-receiver
  namespace: {{ namespace }}
spec:
  ports:
    - name: check-receiver
      port: 8080
      protocol: TCP

  selector:
    app: check-receiver
