apiVersion: v1
kind: Secret
metadata:
  name: restya
  namespace: {{ namespace }}
type: Opaque
data:
  postgres_user: {{ ['Privat', 'NetCup', 'kube', namespace, 'postgresql'] | keepass('username') | base64 }}
  postgres_pass: {{ ['Privat', 'NetCup', 'kube', namespace, 'postgresql'] | keepass('password') | base64 }}
