apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: restya
  name: restya
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: restya
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restya
    spec:
      containers:
      - name: restya
        image: mazdermind/docker-restyaboard
        env:
        - name: DB_HOST
          value: postgres

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: restya
              key: postgres_user

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: restya
              key: postgres_pass

        - name: DB_NAME
          value: restya

        - name: SMTP_RELAYHOST
          value: forwarder.mail-forwarder.svc.cluster.local


        - name: TZ
          value: "Europe/Berlin"

        volumeMounts:
        - mountPath: /var/www/html/media
          name: media

      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: restya-media
