apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www
  labels:
    app: www
  namespace: www-hochzeit
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
